next_photo: str = "Следующие фото для проверки"
new_task_notification: str = "Новая задача на модерации"
cancel: str = "Отмена"
close: str = "Закрыть"
ok: str = "Окей"
reject: str = "Отклонить"
approve: str = "Одобрить"
